export {
  MinimizedProfileDraftSchema,
  ObservedCandidateFactSchema,
  ProfileCapabilitiesSchema,
  ProfileCapabilityReportSchema,
  ProfileDraftSchema,
  ProfileFactSchema,
  ProfileInputSchema,
  ProfileMinimizationResultSchema,
  ProfilePreferenceInputSchema,
  ProfilePreferenceSchema,
  ProfileRequestEvidenceSchema,
  ProfileTermRefSchema,
  PROFILE_CONTRACT_VERSION,
} from './contracts.js';
export type {
  MinimizedProfileDraft,
  ObservedCandidateFact,
  ProfileCapabilityReport,
  ProfileFact,
  ProfileInput,
  ProfileMinimizationResult,
  ProfilePreference,
  ProfilePreferenceInput,
  ProfileRequestEvidence,
  ProfileTermRef,
  StructuredProfile,
} from './contracts.js';
export { canonicalProfileTermKey, minimizeProfile } from './minimize.js';
export type { MinimizeProfileOptions } from './minimize.js';
export { PROFILE_CAPABILITY_REPORT, processProfileRequest } from './service.js';
export type { ProcessProfileRequestOptions } from './service.js';
export {
  LOCAL_PROFILE_ID,
  PROFILE_PERSISTENCE_CONTRACT_VERSION,
  ProfileStoreError,
  ProfileStoreErrorCodeSchema,
  ProfileCorrectionInputSchema,
  SaveAdoptedProfileInputSchema,
  DeleteAdoptedProfileInputSchema,
  ResetProfileStoreInputSchema,
  factId,
  preferenceId,
  correctionId,
  revisionId,
  provenanceId,
  packetId,
  MemoryKeyProvider,
  createSqlCipherOpener,
  applyMigrations,
  MIGRATION_VERSION,
  V1_CHECKSUM,
  createProfileStore,
} from './persist/index.js';
export type {
  ProfileId,
  ProfileRevisionId,
  ProfileFactId,
  ProfilePreferenceId,
  ProfileCorrectionId,
  ProfileProvenanceId,
  SavedProfilePacketId,
  ProfileCorrectionInput,
  SaveAdoptedProfileInput,
  DeleteAdoptedProfileInput,
  ResetProfileStoreInput,
  ProfileStoreErrorCode,
  ProfileKeyProvider,
  ProfileDatabaseOpener,
  ProfileDatabase,
  ProfileStoreDeps,
  AdoptedProfileSnapshot,
  ProfileStore,
} from './persist/index.js';
